"""empty message

Revision ID: 9ce08949a38d
Revises: 
Create Date: 2023-10-23 00:58:48.129257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ce08949a38d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('stock_address', sa.String(length=120), nullable=False),
    sa.Column('delivery_address', sa.String(length=120), nullable=False),
    sa.Column('cargo_type', sa.String(length=40), nullable=False),
    sa.Column('update_status_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fio', sa.String(length=120), nullable=False),
    sa.Column('free', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drivers')
    op.drop_table('orders')
    # ### end Alembic commands ###
